name: Bug Report
description: File a bug report
title: "[BUG REPORT]"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Your telegram username or email ID.
      placeholder: ex. @username or email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of pykillerx are you running?
      options:
        - "0.1.14"

    validations:
      required: true
  - type: dropdown
    id: hosted
    attributes:
      label: Hosted On
      description: You are hosting kyosuke on Which Platform?
      options:
        - Vps
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Acknowledgement
      description: By submitting this issue, you agree that you have read the [docs](https://randydev.tech) and gone through the [deploy tutorial](https://t.me/RendyProjects) at first.
      options:
        - label: I have followed all of the above steps.
          required: true
